# Generated by Django 5.1.4 on 2025-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Имя')),
                ('password', models.CharField(max_length=120, verbose_name='Пароль')),
            ],
        ),
    ]
